name: VanVinh-Build-Pro
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Theos
        run: |
          bash -c "$(curl -fsSL https://raw.githubusercontent.com/theos/theos/master/bin/install-theos)"
          echo "THEOS=/Users/runner/theos" >> $GITHUB_ENV

      - name: Setup SDK
        run: |
          mkdir -p /Users/runner/theos/sdks
          # Sử dụng link SDK khác ổn định hơn
          curl -L https://github.com/theos/sdks/archive/master.tar.gz --output sdks.tar.gz
          tar -xf sdks.tar.gz --strip-components=1 -C /Users/runner/theos/sdks
          rm sdks.tar.gz

      - name: Build Dylib
        run: |
          export THEOS=/Users/runner/theos
          make FINALPACKAGE=1

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: VanVinh-KeyAuth-Dylib
          path: .theos/obj/*.dylib
